ruby '2.1.1'
source 'https://rubygems.org'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'
gem 'dotenv'

gem 'activesupport', '~>4.1'
gem 'activerecord', '~>4.1'

gem 'rake'
gem 'rspec'
gem 'httparty'
gem 'gcm'

gem 'shotgun'
gem 'bcrypt'

group :test do
  gem 'faker'
  gem 'rspec'
end
